name: Build and Test

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 20
      - run: yarn
      - run: yarn build

  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: yarn
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.4
        with:
          docker_version: 20.10.3
      - uses: tpluscode/setup-lando@v0.1.1
        with:
          version: v3.6.4
          healthcheck: http://db.wikibus.lndo.site/
          timeout: 30000
      - run: yarn bootstrap
      - run: yarn test
