name: Heroku

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"
    steps:
      - uses: actions/checkout@v3
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: wikibus2
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
